
# This file is generated by hitl_msg_gen.py

from messages.abstract_message import AbstractMessage

import can  # pip install python-can    

class DemoPacket(AbstractMessage):

    can_id = 0x420
    length = 8
    period = 0.0  # TODO: not implemented yet!

    @property
    def battery_voltage(self):
        return self._get_uint16(byte=0)

    @battery_voltage.setter
    def battery_voltage(self, value):
        self._set_uint16(byte=0, value=value)

    @property
    def aux_voltage(self):
        return self._get_uint16(byte=2)

    @aux_voltage.setter
    def aux_voltage(self, value):
        self._set_uint16(byte=2, value=value)

    @property
    def current(self):
        return self._get_float(byte=4)

    @current.setter
    def current(self, value):
        self._set_float(byte=4, value=value)
