
# This file is generated by hitl_msg_gen.py

from messages.abstract_message import AbstractMessage

import can  # pip install python-can    

class ThunderstruckStatusMessage(AbstractMessage):

    can_id = 0x18eb2440
    length = 8
    period = 0.0  # TODO: not implemented yet!

    @property
    def STATUS_FLAGS(self):
        return self._get_uint8(byte=0)

    @STATUS_FLAGS.setter
    def STATUS_FLAGS(self, value):
        self._set_uint8(byte=0, value=value)

    @property
    def CHARGE_FLAGS(self):
        return self._get_uint8(byte=1)

    @CHARGE_FLAGS.setter
    def CHARGE_FLAGS(self, value):
        self._set_uint8(byte=1, value=value)

    @property
    def OUTPUT_VOLTAGE(self):
        return self._get_uint16(byte=2)

    @OUTPUT_VOLTAGE.setter
    def OUTPUT_VOLTAGE(self, value):
        self._set_uint16(byte=2, value=value)

    @property
    def OUTPUT_CURRENT(self):
        return self._get_uint16(byte=4)

    @OUTPUT_CURRENT.setter
    def OUTPUT_CURRENT(self, value):
        self._set_uint16(byte=4, value=value)

    @property
    def CHARGER_TEMP(self):
        return self._get_uint8(byte=6)

    @CHARGER_TEMP.setter
    def CHARGER_TEMP(self, value):
        self._set_uint8(byte=6, value=value)

    @property
    def RESERVED(self):
        return self._get_uint8(byte=7)

    @RESERVED.setter
    def RESERVED(self, value):
        self._set_uint8(byte=7, value=value)
