
# This file is generated by hitl_msg_gen.py

from messages.abstract_message import AbstractMessage

import can  # pip install python-can    

class TrackerData(AbstractMessage):

    can_id = 0x600
    length = 8
    period = 0.0  # TODO: not implemented yet!

    @property
    def array_voltage(self):
        return self._get_uint16(byte=0)

    @array_voltage.setter
    def array_voltage(self, value):
        self._set_uint16(byte=0, value=value)

    @property
    def array_current(self):
        return self._get_uint16(byte=2)

    @array_current.setter
    def array_current(self, value):
        self._set_uint16(byte=2, value=value)

    @property
    def battery_voltage(self):
        return self._get_uint16(byte=4)

    @battery_voltage.setter
    def battery_voltage(self, value):
        self._set_uint16(byte=4, value=value)

    @property
    def temperature(self):
        return self._get_uint16(byte=6)

    @temperature.setter
    def temperature(self, value):
        self._set_uint16(byte=6, value=value)
